image: saaj/snake-tank
pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install redis-server memcached libmemcached-dev
          - service redis-server start
          - service memcached start
          - tox
